### ISSUE TITLE
Manually validate blockchain addresses

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oss-directory#29]
# Describe the feature you'd like to request
A new blockchain address added to OSS directory should be validated to confirm it has the appropriate `type` assigned to it.

# Describe the solution you'd like
The primary types we are interested in are:
- EOA
- Safe
- Smart Contract (built by the project)
- Contract Factory (a smart contract the project has deployed that creates other smart contracts)

# Describe alternatives you've considered
n/a

**Comment by ccerv1** [comment]
FYI, this [utility script](https://github.com/hypercerts-org/oso/blob/main/indexer/utilities/dune-address-indexer/src/address_tagging.py) uses Etherscan and Alchemy APIs for confirming if an address is an EOA or a contract. If it's a contract, it also tries to get the name.

Future versions could check if a `creator` EOA has deployed a contract from it and if a `contract` is a `factory`.

**Comment by ccerv1** [comment]
Steps:
- Clean up some of the factories that are reused, eg, deterministic deployers
- Generate latest Dune contract exports for OP and ARB
- Rebuild OSSD to validate each assignment

**Comment by ryscheng** [comment]
For now, just a python script we can run ad-hoc
