### ISSUE TITLE
Missing project hildr-optimism-java

### ISSUE THREAD

**Issue by GrapeBaBa** [opensource-observer/oss-directory#433]
Didn't see our project `hildr-optimism-java` in https://docs.opensource.observer/blog/impact-of-retro-funding/#bonus-project-activity-heatmap, want to know why.

**Comment by ccerv1** [comment]
hey there! I found you
<img width="628" alt="image" src="https://github.com/user-attachments/assets/3172cace-5fae-4721-825f-7ccb6f63f3ab">
<img width="344" alt="image" src="https://github.com/user-attachments/assets/a6605dd9-6bd2-4fd9-8b71-3826b631b362">

**Comment by GrapeBaBa** [comment]
@ccerv1 why can't I see it？
![image](https://github.com/user-attachments/assets/1aa4be08-8fcc-4cfd-b3f6-bad88387df70)

**Comment by ccerv1** [comment]
Ahhhh! The viz seems to be inconsistent with which projects it shows / which it hides. I've fixed this in a PR I'm making write now. Will tweet and tag you :)
https://github.com/opensource-observer/oso/pull/1813
