### ISSUE TITLE
Script to populate oss-directory with RetroPGF3 projects

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oss-directory#86]
After the RPGF3 application period is over, we should index the projects' EAS attestations and identify any new and/or updated projects. The current version of the [EAS schema](https://gist.github.com/jakim929/d8269973aa87862fa91037d3be3c4d7f) transcribes the following:

```
{
    applicantType: "PROJECT" | "INDIVIDUAL";
    displayName: string;
    websiteUrl: string;
    bio: string;
    contributionDescription: string;
    contributionLinks: {
        type: "CONTRACT_ADDRESS" | "GITHUB_REPO" | "OTHER";
        url: string;
        description: string;
    }[];
    impactCategory: ("OP_STACK" | "COLLECTIVE_GOVERNANCE" | "DEVELOPER_ECOSYSTEM" | "END_USER_EXPERIENCE_AND_ADOPTION")[];
    impactDescription: string;
    impactMetrics: {
        description: string;
        number: number;
        url: string;
    }[];
    fundingSources: ({
        type: "GOVERNANCE_FUND" | "PARTNER_FUND" | "RETROPGF_2";
        currency: "OP";
        amount: number;
        description?: string | undefined;
    } | {
        type: "RETROPGF_1" | "REVENUE" | "OTHER";
        currency: "USD";
        amount: number;
        description?: string | undefined;
    })[];
    payoutAddress: string;
    understoodKYCRequirements: boolean;
    understoodFundClaimPeriod: boolean;
    certifiedNotDesignatedOrSanctionedOrBlocked: boolean;
    certifiedNotSponsoredByPoliticalFigureOrGovernmentEntity: boolean;
    certifiedNotBarredFromParticipating: boolean;
}
```

We would care about the following for `PROJECT` applicants:

- `displayName`
- `contributionsLinks` to GithHub repos
- `contributionsLinks` to Contract Addresses
- `impactCategory` (as these can be mapped to sub-collections within Optimism)
- `fundingSources` (we need to be able to trace back the past tokens received by the project, eg, from RPGF2)
- `payoutAddress`

**Comment by ryscheng** [comment]
Copied from https://github.com/hypercerts-org/hf-private/issues/53

**Comment by ccerv1** [comment]
This is 50% complete per #107, however, would like to make a script that can review existing projects and update them based on new info submitted during RPGF3

**Comment by ccerv1** [comment]
https://github.com/opensource-observer/oss-directory/commit/97f453d6c4bfde4306166aae9b1652b6eb56b3c8
